[profile.default]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
no_match_path = "src/*"
evm_version = 'cancun'
optimizer = true
optimizer_runs = 1
viaIR = false
gas_limit = 9223372036854775807
eth_rpc_url = "https://eth.public-rpc.com"
auto_detect_remappings = false

[profile.ci_test]
fork_block_number = 18963715

[profile.ci_sizes]
optimizer_runs = 1
test = 'DO_NOT_COMPILE'

[profile.ci_sizes_ir]
optimizer_runs = 200
test = 'DO_NOT_COMPILE'
viaIR = true

[fuzz]
# temporary workaround while we figure out perf issues + configure different test sets + profiles
runs = 30
max_test_rejects = 9_999_999
[rpc_endpoints]
sepolia = 'https://eth-sepolia.g.alchemy.com/v2/VN5K96b647acOyIXfX45zBdO53Dx7ZKm'